### ISSUE TITLE
Changing to imperial units (Fahrenheit) doesn't actually do anything

### ISSUE THREAD

**Issue by Sipesy** [vatsa287/cli-weather#17]
Hi, was trying this out when I realized that imperial units were far lower than they should be. Upon inspection, the same numbers are given regardless of units selected:

`user@solus ~ $ cli-weather city London -u F`

gives

`Current temparature in London is 21.1 Fahrenheit`

while

`user@solus ~ $ cli-weather city London -u M`

currently gives

`Current temparature in London is 21.1 celsius`

Unless I missed an SI announcement, I don't think 21F is the same as 21C :sweat_smile:

**Comment by vatsa287** [comment]
First of all thanks for trying 🤩. This project was not in maintenance and the backend API usage has been changing rapidly. Will update you by this weekend.

**Comment by vatsa287** [comment]
Initial observation is that cli-weather is checking for metrics choices in uppercase only [M, S, F] and then setting the required string for query-string for API URL. You can add smaller case options too. 
Reference files are get_by_city.py and get_by_postalcode.py

**Comment by vatsa287** [comment]
@Sipesy The version 0.1.9 fixes this issue. Give a try.
